

hydra:
  run:
    dir: outputs/finetune_baseline
    

# 手法名
method: 
  name: "finetune"


model:
  type: "resnet18"



dataset:
  type: "cifar100"
  num_classes: 100
  data_folder: '/home/kouyou/datasets/'
  size: 32
  drop_last: True
  start_index: 0



optimizer:
  train:
    learning_rate: 1e-2
    weight_decay: 1e-4
    momentum: 0.9
    eta: 0.005
    batch_size: 16
    start_epoch: 0
    epochs: 20
    scheduler_type: "cos"
    scheduler_exit_decay: 0
  
scheduler:
  train:
    milestones: [16]
    gamma: 0.1


continual:
  n_cls: 100
  n_task: 10
  cls_per_task: 10
  buffer_type: "ring"
  buffer_size: 1000
  target_task: 



linear:
  dataset: "imagenet21k"
  task_id: []
  n_task: 100
  num_workers: 10
  train:
    batch_size: 1024
    epochs: 100
    learning_rate: 1.0
    momentum: 0.9
    weight_decay: 0
    schedule: [60, 80]
    eta: 0.005
    cos: True



log:
  name: 
  base: "baseline"
  model: "model"
  result: "result"
  base_path: 
  model_path: 
  explog_path: 
  mem_path: 
  result_path: 
  save_freq: 0.005
  save_freq_mints: 20
  print_freq: 20
  resume: True


ddp:
  local_rank: 
  use_ddp: 
  world_size: 


amp:
  use_amp: False
  dtype: "fp16"        # "fp16" か "bf16"（A100/H100 や RTX 40xx は bf16 推奨）
  grad_scaler: true    # bf16 のときは自動的に無視されます



seed: 777
date: 2025_1027
workers: 64


debug: False


